SWIFT_CISB_CHANNEL_ISTAG="edge"
SWIFT_CISB_CHANNEL_ISCHANGEREQUEST="unstable"
SWIFT_CISB_CHANNEL_ISMASTER="development"

SWIFT_CISB_CHANNEL_ISTEST="unstable"
SWIFT_CISB_CHANNEL_ISTEST_REGEX="^bugfix"

SWIFT_CISB_CHANNEL_ISFEATURE="unstable"
SWIFT_CISB_CHANNEL_ISFEATURE_REGEX="^feature"

SWIFT_CISB_CHANNEL_ISRELEASE="stable"
SWIFT_CISB_CHANNEL_ISRELEASE_REGEX="^release"
