name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  IMAGE_TAG: swift/avionics_sim:latest
  DOCKER_TEST: .devcontainer/docker_test.yml
  CI_CONTAINER: ci_container

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .devcontainer/Dockerfile
          tags: ${{env.IMAGE_TAG}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/avionics_sim_image.tar
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: avionics_sim_image
          path: /tmp/avionics_sim_image.tar
          
      - name: Load image
        run: |
          docker load --input /tmp/avionics_sim_image.tar
          docker image ls -a
      - name: Inspect Image
        run: |
          docker image inspect ${{env.IMAGE_TAG}}
      - name: Test Built Docker Image
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
          container-structure-test test --config ${{env.DOCKER_TEST}} --image "${IMAGE_TAG}"
  build:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: avionics_sim_image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/avionics_sim_image.tar
          docker image ls -a
      - name: Start Container
        run: docker run --name ${{env.CI_CONTAINER}} -dit -v $PWD:/work_dir -w/work_dir ${{env.IMAGE_TAG}} /bin/bash
    
      - name: Configure in Container
        run: |
          docker exec ${{env.CI_CONTAINER}} ls -la && ls -la /
          docker exec ${{env.CI_CONTAINER}} cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
      - name: Build in Container
        run: docker exec ${{env.CI_CONTAINER}} cmake --build build --config ${{env.BUILD_TYPE}}
      
      - name: Test in Container
        run: docker exec ${{env.CI_CONTAINER}} bash -c "cd build && ctest"

      - name: Stop Container
        run: docker stop ${{env.CI_CONTAINER}}