
name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Build docker image
      run: docker build -t ci_container . < .devcontainer/Dockerfile
    
    - name: Start Container
      run: docker run --name my_container -dit -v $PWD:/work_dir -w/work_dir ci_container /bin/bash
    
    - name: Configure in Container
      run: docker exec my_container cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Build in Container
      run: docker exec my_container cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Stop Container
      run: docker stop my_container