name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI/CD Automation
    steps:
      - uses: actions/checkout@v2
      - name: Automation step 1
        uses: ./.github/
